# --- CONFIGURACIÓN DEL PROYECTO ---
# RUTA DE SEGURIDAD: Guardamos directamente en Drive.
# Si Colab se desconecta, los pesos 'best.pt' y 'last.pt' estarán aquí a salvo.
project_name: "/content/drive/MyDrive/IPDI/Trabajo Final/Resultados_YOLO"
experiment_name: "YOLOv8n_Exp1_FullAug"

# --- RUTAS ---
# Esta ruta será sobrescrita dinámicamente por el main.py cuando inyecte el dataset descomprimido
data_yaml_path: "dataset/data.yaml" 

# --- MODELO ---
model_version: "yolov8n.pt"
img_size: 640

# --- HIPERPARÁMETROS DE HARDWARE ---
epochs: 300              # Techo alto, regulado por 'patience'
batch_size: 80           # 64 puede ser inestable si usas cache en RAM + Drive I/O. 32 es seguro.
workers: 10               # Límite seguro para Colab
cache: True              # Carga imágenes en RAM para compensar la lentitud de escribir en Drive
device: 0                

# --- OPTIMIZADOR ---
optimizer: "Adam"        
lr0: 0.001               
momentum: 0.937
weight_decay: 0.0005

# --- ESTRATEGIA DE PARADA (PACIENCIA) ---
patience: 20             # Si no mejora en 20 épocas, se detiene.

# --- AUGMENTATION (Nivel 2 - Agronómico) ---
degrees: 20.0            # Rotación
flipud: 0.5              # Espejo vertical
fliplr: 0.5              # Espejo horizontal
scale: 0.5               # Escala +/- 50%
translate: 0.1           # Traslación
mosaic: 1.0              # Siempre activo en YOLOv8
mixup: 0.15              # Mezcla de imágenes
copy_paste: 0.15         # Copy-Paste 

# --- SISTEMA ---
seed: 42