# --- CONFIGURACIÓN DEL PROYECTO ---
project_name: "Proyecto_IPDI"
experiment_name: "YOLOv8n_Adam_Cos_v1"

# --- RUTAS ---
# IMPORTANTE: Asegúrate de que este archivo exista y tenga las rutas absolutas o relativas correctas a tus imágenes
data_yaml_path: "dataset/data.yaml" 

# --- MODELO ---
model_version: "yolov8n.pt"  # Nano para el mini-proyecto (velocidad > precisión extrema)
img_size: 640

# --- HIPERPARÁMETROS DE ENTRENAMIENTO (Basado en Khedkar et al.) ---
epochs: 150              # Suficiente para estabilizar la función de pérdida
batch_size: 16           # Ajustar según VRAM de tu GPU
optimizer: "Adam"        # Mejor convergencia inicial en datasets complejos
lr0: 0.001               # Learning Rate inicial
momentum: 0.937
weight_decay: 0.0005
patience: 25             # Early stopping para evitar overfitting

# --- AUGMENTATION (Nativa de YOLO - ON THE FLY) ---
# Justificación Agronómica: 
# - No rotamos 90 grados (las naranjas cuelgan, no flotan en gravedad cero).
# - Flip horizontal OK (simetría esférica).
# - Flip vertical OFF (el cielo está arriba, el suelo abajo).
degrees: 15.0            # Rotación leve (viento/ángulo de cámara)
fliplr: 0.5              # Espejo horizontal
flipud: 0.0              # Espejo vertical DESACTIVADO
mosaic: 1.0              # Vital para detectar objetos pequeños
mixup: 0.1               # Robustez ante oclusiones

# --- SISTEMA ---
seed: 42                 # Reproducibilidad estricta
device: 0                # GPU ID (usar 'cpu' si no hay GPU dedicada)
workers: 4